export const ErrorCodes = {
  // 공통
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',

  // Auth
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_NOT_ACTIVE: 'ADMIN_NOT_ACTIVE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
